app = 'udp-server'
primary_region = 'iad'

[build]

[[services]]
  protocol = "udp"
  internal_port = 5000
  auto_stop_machines = 'off'
  min_machines_running = 1
  [[services.ports]]
    port = 5000
[[vm]]
  size = 'shared-cpu-1x'
